---
title: "Final Project"
subtitle: "Water Temperature"
author: "Zhanylai Turatkhan kyzy, Julia Kagiliery, Yilun Zhu"
output: pdf_document
geometry: margin=2.54cm
---

**Introduction**


**Motivation/relevance of the study**


**Objectives**


**Dataset Information**


**Methodology / Analysis**


**Description**
1. SARIMA model
2. TBATS model
3. ETS model
4. SSES model
5. NN

```{r, echo=FALSE}
library(ggplot2)
library(readxl)
library(cowplot)
library(tidyverse)
library(lubridate)
library(dplyr)
library(knitr)
library(caret)
library(forecast)
library(zoo)
```

```{r, echo=FALSE}
file_path <- "/home/guest/TSA_Janka/WaterTemperature_TSA_FinalProject/Monthly Data_Temperature2011-2021.xlsx"
temperature_data <- read_excel(file_path, sheet = "Sheet1")
head(temperature_data)
```
```{r, echo=FALSE}
temperature_ts <- ts(temperature_data$Temperature,
                     start = c(2011, 1), frequency = 12)
```

```{r, echo=FALSE}
plot(temperature_ts)
```
```{r}
str(temperature_ts)
```
```{r}
split_point <- round(length(temperature_ts) * 0.8)
train_ts <- window(temperature_ts, end=c(2019, 8))
test_ts <- window(temperature_ts, start=c(2019, 9))
```
```{r}
start(train_ts)
end(train_ts)
```
```{r}
start(test_ts)
end(test_ts)
```

```{r, echo=FALSE}
#SARIMA autofit
sarima_model <- auto.arima(train_ts)
print(summary(sarima_model))
```
```{r}
checkresiduals(sarima_model)
```

```{r}
h <- length(test_ts)
sarima_forecast <- forecast(sarima_model, h=h)
```
```{r}
autoplot(temperature_ts, series = "Original") +
  autolayer(sarima_forecast$mean, series = "SARIMA forecast") +
  ylab("Water Temperature") +
  ggtitle("SARIMA modeling")
```

```{r}
checkresiduals(sarima_forecast)
```
```{r}
forecast_accuracy <- accuracy(sarima_forecast, test_ts)
print(forecast_accuracy)
```
```{r}
# STL + ETS
ets_model <- stlf(train_ts, h=h)
```
```{r}
autoplot(temperature_ts, series = "Original") +
  autolayer(ets_model, series = "STL + ETS", PI=FALSE) +
  ylab("Water Temperature") +
  ggtitle("STL + ETS modeling")
```

```{r}
stlf_accuracy <- accuracy(ets_model, test_ts)
print(stlf_accuracy)
```
```{r}
checkresiduals(ets_model)
```

